In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
annot_df = pd.read_csv('../neuron_annotations.csv', index_col=0)
annot_df

,experiment,Repeats,Idents,exp_time,condition,date
20181215_CLK856_LD_ZT14_AR07_ACAGGA,CLK856_LD,LD_2,29:LPN,ZT14,LD,2018-12-15
20181215_CLK856_LD_ZT14_AR07_CTTCTG,CLK856_LD,LD_2,29:LPN,ZT14,LD,2018-12-15
20181231_CLK856_LD_ZT14_AR02_GTACCA,CLK856_LD,LD_1,29:LPN,ZT14,LD,2018-12-31
20181231_CLK856_LD_ZT14_AR02_TCCTTC,CLK856_LD,LD_1,29:LPN,ZT14,LD,2018-12-31
20181231_CLK856_LD_ZT14_AR08_AGACAG,CLK856_LD,LD_1,29:LPN,ZT14,LD,2018-12-31
...,...,...,...,...,...,...
20190710_CLK856_DD_CT06_AR04_GTCTTC,CLK856_DD,DD_1,1:DN1p_CNMa,CT06,DD,2019-07-10
20190710_CLK856_DD_CT06_AR04_TCCTTC,CLK856_DD,DD_1,1:DN1p_CNMa,CT06,DD,2019-07-10
20190719_CLK856_DD_CT06_AR18_GTCTTC,CLK856_DD,DD_2,1:DN1p_CNMa,CT06,DD,2019-07-19
20190814_CLK856_DD_CT06_AR19_TCTGCA,CLK856_DD,DD_2,1:DN1p_CNMa,CT06,DD,2019-08-14
20190814_CLK856_DD_CT06_AR20_CACTTC,CLK856_DD,DD_2,1:DN1p_CNMa,CT06,DD,2019-08-14